version: 2.1
orbs:
  node: circleci/node@3.0.1
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install:
          node-version: 12.18.2
      - run: node --version
      - run: npm --version
      - run: npm install
      - run: npm run type-check
      - run: npm test
workflows:
    build-and-test:
      jobs:
        - build-and-test
