version: 2.1
executors:
  my-node-v12:
    docker:
      - image: circleci/node:12.18.2
  my-node-v10:
    docker:
      - image: circleci/node:10.19.0
orbs:
  node: circleci/node@3.0.1
jobs:
  build-and-test-on-node-v12:
    executor:
      name: my-node-v12
    steps:
      - checkout
      - run: node --version
      - run: npm --version
      -
        node/install-packages:
          cache-version: node12-v1
      - run: npm run type-check
      - run: npm test
  build-and-test-on-node-v10:
    executor:
      name: my-node-v10
    steps:
      - checkout
      - run: node --version
      - run: npm --version
      -
        node/install-packages:
          cache-version: node10-v1
      - run: npm run type-check
      - run: npm test
workflows:
  build-and-test:
    jobs:
      - build-and-test-on-node-v12
      - build-and-test-on-node-v10
