version: 2.1
executors:
  my-node-v12:
    docker:
      - image: circleci/node:12.18.2
orbs:
  node: circleci/node@3.0.1
jobs:
  build-and-test:
    executor:
      name: my-node-v12
    steps:
      - checkout
      - run: node --version
      - run: npm --version
      - node/install-packages
      - run: npm run type-check
      - run: npm test
workflows:
  build-and-test:
    jobs:
      - build-and-test
